### ISSUE TITLE
タネをかえなかったときの挙動

### ISSUE THREAD

**Issue by yuuki-foll** [yuuki-foll/Grow-plants-web-app#119]
「タネをかえる」ボタンを押した後に種を選ばずに閉じたり同じ種を選んだりすると、「しあわせメーター」や体力は初期化されるが植物がタネ状態に戻らない（画像が更新されないだけでそのあとに話しかけると正しい状態に切り替わる）

**Comment by yuji-matsunami** [comment]
修正完了しました
